#!/bin/bash

clipboard=$(xclip -o -selection clipboard)

if [[ $clipboard == *github.com* ]]; then
  echo $clipboard  
  git_command="git clone $clipboard --single-branch"
  eval $git_command
  cd $(basename $clipboard .git)
  if [ -f .gitmodules ]; then
    git submodule update --init --recursive
    git submodule foreach 'branch=$(git branch -r | grep -m1 origin/HEAD | sed "s/.*origin\///") && git checkout $branch && git pull origin $branch'
  fi
elif [[ $clipboard == *bitbucket.org* ]]; then
  echo $clipboard  
  git_command="$clipboard --single-branch"
  eval $git_command
  cd $(basename $clipboard .git)
  if [ -f .gitmodules ]; then
    git submodule update --init --recursive
    git submodule foreach 'branch=$(git branch -r | grep -m1 origin/HEAD | sed "s/.*origin\///") && git checkout $branch && git pull origin $branch'
  fi
else
  echo "Clipboard does not contain a git repository"
fi
