#!/bin/bash

function commit(){
  git status

  echo "${tgreen}Choose a commit message type:${treset}"
  echo "------------------------------------------"
  echo "${tblue}1) feat: (A new feature)${treset}"
  echo "${tblue}2) upd: (An update to an existing feature)${treset}"
  echo "${tyellow}3) bug-fix: (A bug fix)${treset}"
  echo "${tyellow}4) fix: (A hotfix)${treset}"
  echo "${tgreen}5) core: (An install a new package)${treset}"
  echo "${tgreen}6) lazygit${treset}"
  echo "${tmagenta}7) exit: (Exit the script)${treset}"
  echo "------------------------------------------"
  read -p "${tgreen}What commit message would you like to use? ${treset}" message

  if [ "$message" == "1" ]; then
    echo "${tgreen}You chose: feat${treset}"
    read -p "${tgreen}What is the commit message? ${treset}" message
    git add .
    git commit -a -m "feat: $message"
    git push
  elif [ "$message" == "2" ]; then
    echo "${tgreen}You chose: upd${treset}"
    read -p "${tgreen}What is the commit message? ${treset}" message
    git add .
    git commit -a -m "upd: $message"
    git push
  elif [ "$message" == "3" ]; then
    echo "${tgreen}You chose: bug-fix${treset}"
    read -p "${tgreen}What is the commit message? ${treset}" message
    git add .
    git commit -a -m "bug-fix: $message"
    git push
  elif [ "$message" == "4" ]; then
    echo "${tgreen}You chose: fix${treset}"
    read -p "${tgreen}What is the commit message? ${treset}" message
    git add .
    git commit -a -m "fix: $message"
    git push
  elif [ "$message" == "5" ]; then
    echo "${tgreen}You chose: core${treset}"
    read -p "${tgreen}What is the commit message? ${treset}" message
    git add .
    git commit -a -m "core: $message"
    git push
  elif [ "$message" == "6" ]; then
    lazygit
  elif [ "$message" == "7" ]; then
    echo "${tgreen}Exiting script${treset}"
    exit 0
  else
    echo "${tred}Invalid option${treset}"
    commit
  fi
}

if [ -f ".gpgrc" ]; then
  list=$(cat .gpgrc)
  for file in $list; do
    if [ ! -f "$file" ]; then
      echo "${tred}File $file not found${treset}"
      exit 1
    fi
  done
  echo "${tgreen}Files found${treset}"
  commit
else
  commit
  exit 1
fi

