#!/bin/bash

if docker ps -a | grep -q '[0-9]'; then
  echo "${tmagenta}There are active docker containers:${treset}"
  docker ps -a
  echo "${tmagenta}Stopping all docker containers...${treset}"
  docker stop $(docker ps -q)
  echo "${tgreen}All docker containers stopped.${treset}"
fi

sudo shutdown -h now
