#!/bin/bash

## check if have ~/.tmux/plugins directory
if [ ! -d "$HOME/.tmux/plugins" ]; then
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
  echo "${tgreen}tmux plugins already installed.${treset}"
fi


sessions=()
while IFS= read -r line; do
    sessions+=("$line")
done < <(tmux list-sessions)

## check if there are any sessions
if [ ${#sessions[@]} -eq 0 ]; then
    echo "${tmagenta}No tmux sessions found.${treset}"
    tmux
    exit 1
fi

tmux list-sessions

read -p "${tblue}Select or create or delete, s/d: ${treset}" choice

if [[ $choice == "s" ]]; then
    echo "${tblue}Select a session to attach to:${treset}"
    # select with fzf
    session_name=$(printf '%s\n' "${sessions[@]}" | fzf --height 40% --reverse --inline-info)
    if [ -z "$session_name" ]; then
        echo "${tmagenta}No session selected.${treset}"
        exit 1
    fi
    session_name=$(echo "$session_name" | awk -F: '{print $1}')
    tmux attach-session -t "$session_name"
  elif [[ $choice == "d" ]]; then
    echo "${tgreen}Select a session to delete:${treset}"
    # select with fzf
    session_name=$(printf '%s\n' "${sessions[@]}" | fzf --height 40% --reverse --inline-info)
    if [ -z "$session_name" ]; then
        echo "${tmagenta}No session selected.${treset}"
        exit 1
    fi
    session_name=$(echo "$session_name" | awk -F: '{print $1}')
    tmux kill-session -t "$session_name"
else
    echo "${tmagenta}Invalid choice. Please enter 'c' or 's'.${treset}"
fi

tmux ls
